# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        work_dir:
          - ./lesson1/homework
          - ./lesson2/homework
          - ./lesson3/homework
          - ./lesson4/homework
          - ./lesson5/homework
          - ./lesson6/homework
          - ./lesson7/homework
          - ./lesson8/homework
          - ./lesson9/homework
          - ./lesson10/homework
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Build
        working-directory: ${{ matrix.work_dir }}
        run: |
          go mod tidy
          go build -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ${{ matrix.work_dir }}

      - name: Test
        working-directory: ${{ matrix.work_dir }}
        run: |
          go mod tidy
          go test -v -race -coverpkg=./... ./...
